name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Install Dependencies
        run: npm ci
        shell: bash
      - name: Build
        run: npm run build
        shell: bash

  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Chekout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Install dependencies
        run: npm ci
        shell: bash
      - name: Run eslint
        run: npm run lint:ci
        shell: bash

  pretteir:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Install dependencies
        run: npm ci
        shell: bash
      - name: Run prettier
        run: npm run format:ci
        shell: bash
